### ISSUE TITLE
GitHub

### ISSUE THREAD

**Issue by foks20** [asadmehdi785/NBA-Trade-Machine#14]
Accidentally worked on master project, how to undo that?

**Comment by elassy** [comment]
Not sure what this issue is actually trying to say. @foks20, could you communicate this a little clearer?

**Comment by foks20** [comment]
the best practice is to not work on the master branch as the master branch holds a working/final product. Team members should create a branch from the master branch which creates a "copy" of it, if a member happens to mess up the code/application, it will not affect others.

**Comment by elassy** [comment]
Ah, I see what you're saying. Well, we kind of took care of that a couple ways, and we touched on this in the final presentation actually, but due to the heavy peer programming we used, coupled with doing it mainly on @asadmehdi785's laptop, committing and pulling from master worked well. We hardly were ever working on the same file at the same time when not together - actually, just about every time we did work on the same file simultaneously it was while peer programming.

Thanks for clarifying that issue @foks20, I'm gonna go ahead and close it, and reference that we should all dig deeper into how to use GitHub more to our advantage for future progress. That being said, I'm pleased with what we learned throughout the semester, and want to congratulate everyone for a job well done: @foks20 @asadmehdi785 @DoctorCandor
